#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Silberburg
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Eine Legende in Nürtingen
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Die Silberburg (SiBu) in dieser Form wie man sie heute kennt, gibt es seit 1980 und wird seit dem von einem Kollektiv verwaltet und betrieben. Das Haus hat neben Kneipenraum und Biergarten auch noch einen Proberaum und drei Wohnungen mit WGs. Im Kneipenraum gibt es ca. 50 Sitzplätze.

Wir MitarbeiterInnen sind ein bunter Haufen von Menschen, die die Silberburg mit dem Konzept des Kneipen-Kollektivs ehrenamtlich betreiben. Wir sind ein offenes Kollektiv, d.h. Gäste können auch VeranstalterInnen werden. Die Idee dahinter ist, einen Raum zu schaffen, in dem jedeR die Möglichkeit hat, eigene Ideen einzubringen und in irgendeiner Form mitmischen kann. Hierfür gibt es eine regelmäßig stattfindende Kneipen-Sitzung, keinE ChefIn bestimmt, wo es lang geht. Neben dem "normalen" Kneipenbetrieb finden vorzugsweise an Samstagen Konzerte, Diskos, Jam-Sessions und andere Veranstaltunge statt. Wenn die Kneipe Gewinn gemacht hat, entscheidet das Kollektiv, für welchen Zweck das überschüssige Geld gespendet wird.citation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: supisibu@web.de
org_street_address: Wilhelmstrasse 1 #Please include suite number on the line below
org_city: Nürtingen
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  72622
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  00497022479306

#SOCIAL MEDIA
org_twitter_username: silberburg
org_facebook_username: silberburg
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: silberburg
tinyletter_username: silberburg

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
